# Generated by Django 5.1.1 on 2024-11-24 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pressure', models.FloatField()),
                ('temperature', models.FloatField()),
                ('image', models.ImageField(upload_to='simulations/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
