# Generated by Django 5.1.1 on 2024-12-09 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='simulation_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
