# Generated by Django 5.1.1 on 2025-05-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_simulation_simulation_result_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulationresult',
            name='stress_image',
        ),
        migrations.RemoveField(
            model_name='simulationresult',
            name='stress_model',
        ),
        migrations.RemoveField(
            model_name='simulationresult',
            name='temp_image',
        ),
        migrations.RemoveField(
            model_name='simulationresult',
            name='temp_model',
        ),
        migrations.RemoveField(
            model_name='simulationresult',
            name='texture_image',
        ),
        migrations.RemoveField(
            model_name='simulationresult',
            name='texture_model',
        ),
        migrations.AddField(
            model_name='simulationresult',
            name='displacement_image',
            field=models.ImageField(null=True, upload_to='simulation_results/'),
        ),
        migrations.AddField(
            model_name='simulationresult',
            name='displacement_model',
            field=models.FileField(null=True, upload_to='simulation_results/'),
        ),
        migrations.AddField(
            model_name='simulationresult',
            name='geometry_image',
            field=models.ImageField(null=True, upload_to='simulation_results/'),
        ),
        migrations.AddField(
            model_name='simulationresult',
            name='mesh_image',
            field=models.ImageField(null=True, upload_to='simulation_results/'),
        ),
        migrations.AddField(
            model_name='simulationresult',
            name='mesh_model',
            field=models.FileField(null=True, upload_to='simulation_results/'),
        ),
        migrations.AddField(
            model_name='simulationresult',
            name='nodal_stress_image',
            field=models.ImageField(null=True, upload_to='simulation_results/'),
        ),
        migrations.AddField(
            model_name='simulationresult',
            name='nodal_stress_model',
            field=models.FileField(null=True, upload_to='simulation_results/'),
        ),
        migrations.AddField(
            model_name='simulationresult',
            name='results_image',
            field=models.ImageField(null=True, upload_to='simulation_results/'),
        ),
        migrations.AlterField(
            model_name='simulationresult',
            name='result_file',
            field=models.FileField(null=True, upload_to='simulation_results/'),
        ),
        migrations.AlterField(
            model_name='simulationresult',
            name='summary',
            field=models.JSONField(default=dict),
        ),
    ]
