# Generated by Django 5.1.1 on 2025-05-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_simulationresult_stress_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationresult',
            name='mesh_image2',
            field=models.ImageField(null=True, upload_to='simulation_results/'),
        ),
    ]
