# Generated by Django 5.1.1 on 2025-05-08 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_simulationresult_mesh_image2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulationresult',
            name='displacement_image',
        ),
        migrations.RemoveField(
            model_name='simulationresult',
            name='displacement_model',
        ),
        migrations.RemoveField(
            model_name='simulationresult',
            name='mesh_image2',
        ),
        migrations.RemoveField(
            model_name='simulationresult',
            name='mesh_model',
        ),
        migrations.RemoveField(
            model_name='simulationresult',
            name='nodal_stress_image',
        ),
        migrations.RemoveField(
            model_name='simulationresult',
            name='nodal_stress_model',
        ),
    ]
