# Generated by Django 5.1.1 on 2025-05-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_results_image_simulationresult_deformation_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulationresult',
            name='geometry_image',
        ),
        migrations.AddField(
            model_name='simulation',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
