# Generated by Django 5.1.1 on 2025-05-30 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_simulationresult_geometry_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='parameters_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
